### ISSUE TITLE
[help] silent error throws during the installation 

### ISSUE THREAD

**Issue by falcucci** [neoclide/coc-prettier#114]
```
:CocInstall coc-prettier
```

checking the `coc` logs:

```
2021-02-26T22:47:29.381 ERROR (pid:94137) [extensions] - TypeError: Cannot read property 'createOutputChannel' of undefined
    at setupErrorHandler (/Users/falcucci/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:1846:38)
    at Object.activate (/Users/falcucci/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:2217:30)
    at Object.activate (/Users/falcucci/projects/dotfiles/src/vim/vim/plugged/coc.nvim/build/index.js:40465:57)
    at Extensions.activate (/Users/falcucci/projects/dotfiles/src/vim/vim/plugged/coc.nvim/build/index.js:40186:19)
    at Extensions.setupActiveEvents (/Users/falcucci/projects/dotfiles/src/vim/vim/plugged/coc.nvim/build/index.js:40361:18)
    at Extensions.activateExtensions (/Users/falcucci/projects/dotfiles/src/vim/vim/plugged/coc.nvim/build/index.js:39787:18)
    at Plugin.init (/Users/falcucci/projects/dotfiles/src/vim/vim/plugged/coc.nvim/build/index.js:22356:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2021-02-26T22:47:29.385 INFO (pid:94137) [plugin] - coc 0.0.78-fc983ce6dd initialized with node: v10.18.1
```

for more informations with `:CocInfo`

```
## versions

vim version: VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 19 2021 18:24:53)
node version: v10.18.1
coc.nvim version: 0.0.78-fc983ce6dd
term: iTerm.app
platform: darwin

## Output channel: snippets

[Info 10:47:29 PM] Using ultisnips directories: UltiSnips /Users/falcucci/.config/coc/ultisnips
[Info 10:47:29 PM] Using ultisnips python command: pyx
```

it started happening suddenly today.

have you any idea about what is happening?

**Comment by fannheyward** [comment]
You're using coc.nvim 0.0.78, a very old version, upgrade your coc.nvim first.

**Comment by falcucci** [comment]
nice catch @fannheyward 

upgraded everything here and worked like a charm.

ty
