### ISSUE TITLE
 Cannot read property 'createOutputChannel' of undefined

### ISSUE THREAD

**Issue by lfv89** [neoclide/coc-prettier#118]
Does anyone have any idea on how to solve this problem?

I already did the re-installation process. This error pops-up every time I open neovim.

```
[coc.nvim] Error on active extension coc-prettier: TypeError: Cannot read property 'createOutputChannel' of undefined
    at setupErrorHandler (/home/lfv89/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:2527:38)
    at Object.activate (/home/lfv89/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:2897:30)
    at Object.activate (/home/lfv89/.vim/plugged/coc.nvim/build/index.js:40465:57)
    at Extensions.activate (/home/lfv89/.vim/plugged/coc.nvim/build/index.js:40186:19)
    at Extensions.setupActiveEvents (/home/lfv89/.vim/plugged/coc.nvim/build/index.js:40361:18)
    at Extensions.activateExtensions (/home/lfv89/.vim/plugged/coc.nvim/build/index.js:39787:18)
    at Plugin.init (/home/lfv89/.vim/plugged/coc.nvim/build/index.js:22356:40)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /home/lfv89/.vim/plugged/coc.nvim/build/index.js:10398:13
```

**Comment by fannheyward** [comment]
Upgrade your coc.nvim to latest release.

**Comment by lfv89** [comment]
Thanks.
