### ISSUE TITLE
import_coc6.window.onDidChangeA ctiveTextEditor is not a function

### ISSUE THREAD

**Issue by Hamm-J** [neoclide/coc-prettier#151]
I am trying to setup coc-prettier for the first time and keep running into the following error: 

`[coc.nvim] Error on activate extension coc-prettier: import_coc6.window.onDidChangeA
ctiveTextEditor is not a function`

I have coc installed via plug and other coc extensions are working just fine. But running `CocInstall coc-prettier` gives me the above error. 

OS: MacOS 12.1
client: nvim 0.6.0
node: 16.13.1

Thank you in advance!

**Comment by Hamm-J** [comment]
Running `CocOpenLog` gives the following output:

2022-05-13T21:38:21.637 ERROR (pid:64177) [extensions] - Error on active extension coc-prettier: TypeError: import_coc6.window.onDidChangeActiveTextEditor is not a function
  1     at PrettierEditService.registerDisposables (/Users/jason/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4506:49)
  2     at Object.activate (/Users/jason/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:5044:153)
  3     at /Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58904:37
  4     at new Promise (<anonymous>)
  5     at Object.activate (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58902:22)
  6     at Extensions.activate (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58621:41)
  7     at Extensions.setupActiveEvents (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58786:22)
  8     at Extensions.activateExtensions (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58253:16)
  9     at Plugin.init (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:68265:30)
 10     at processTicksAndRejections (node:internal/process/task_queues:96:5) TypeError: import_coc6.window.onDidChangeActiveTextEditor is not a function
 11     at PrettierEditService.registerDisposables (/Users/jason/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4506:49)
 12     at Object.activate (/Users/jason/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:5044:153)
 13     at /Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58904:37
 14     at new Promise (<anonymous>)
 15     at Object.activate (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58902:22)
 16     at Extensions.activate (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58621:41)
 17     at Extensions.setupActiveEvents (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58786:22)
 18     at Extensions.activateExtensions (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:58253:16)
 19     at Plugin.init (/Users/jason/.config/nvim/autoload/plugged/coc.nvim/build/index.js:68265:30)
 20     at processTicksAndRejections (node:internal/process/task_queues:96:5)
 21 2022-05-13T21:38:21.659 INFO (pid:64177) [plugin] - coc.nvim 0.0.80-9f6e29b6f9 initialized with node: v16.13.1 after 250ms
 22 2022-05-13T21:38:21.661 ERROR (pid:64177) [node-client] - import_coc5.workspace.languageIds is not iterable TypeError: import_coc5.workspace.languageIds is not iterable
 23     at TextmateProvider.init (/Users/jason/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:2593:50)
 24     at processTicksAndRejections (node:internal/process/task_queues:96:5)
 25     at async Promise.all (index 1)
 26     at async ProviderManager.init (/Users/jason/.config/coc/extensions/node_modules/coc-snippets/lib/index.js:1374:5)
 27 2022-05-13T21:38:23.515 INFO (pid:64177) [services] - registered service "vimlsp"
 28 2022-05-13T21:38:23.516 INFO (pid:64177) [services] - vim language server state change: stopped => starting
 29 2022-05-13T21:38:23.772 INFO (pid:64177) [services] - vim language server state change: starting => running
 30 2022-05-13T21:38:23.778 INFO (pid:64177) [services] - service vimlsp started
 31 2022-05-13T21:38:34.933 INFO (pid:64177) [attach] - receive notification: openLog []

**Comment by fannheyward** [comment]
Your coc.nvim is outdated, upgrade it to latest release please.

**Comment by Hamm-J** [comment]
My apologies! This fixed it. Thank you!

**Comment by not-rusty** [comment]
Ah fixed it also for me. Thanks!

**Comment by weber-s** [comment]
Hello,

I have version `coc-prettier=9.3.1` (latest one) and having the same issue.

```
2022-07-20T09:56:02.368 ERROR (pid:16340) [extensions] - Error on active extension coc-prettier: TypeError: import_coc6.window.onDidChangeActiveTextEditor is not a function
    at PrettierEditService.registerDisposables (/home/XXXX/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4506:49)
    at Object.activate (/home/XXXX/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:5044:153)
    at /home/XXXX/.vim/plugged/coc.nvim/build/index.js:238:1411
    at new Promise (<anonymous>)
    at Object.activate (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:238:1369)
    at N5.activate (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:235:7436)
    at N5.setupActiveEvents (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:235:10720)
    at N5.activateExtensions (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:234:49750)
    at ox.init (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:264:33721)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) TypeError: import_coc6.window.onDidChangeActiveTextEditor is not a function
    at PrettierEditService.registerDisposables (/home/XXXX/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4506:49)
    at Object.activate (/home/XXXX/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:5044:153)
    at /home/XXXX/.vim/plugged/coc.nvim/build/index.js:238:1411
    at new Promise (<anonymous>)
    at Object.activate (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:238:1369)
    at N5.activate (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:235:7436)
    at N5.setupActiveEvents (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:235:10720)
    at N5.activateExtensions (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:234:49750)
    at ox.init (/home/XXXX/.vim/plugged/coc.nvim/build/index.js:264:33721)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

neovim version 0.4.4
