### ISSUE TITLE
[Bug] coc-prettier fails to start

### ISSUE THREAD

**Issue by neery1218** [neoclide/coc-prettier#157]
Hello, thanks for creating this plugin! I get a lot of use from it.
Around a week ago, my coc-prettier extension stopped working. Here's the log from CocInfo:

```vim version: NVIM v0.7.2
node version: v16.14.0
coc.nvim version: 0.0.80-0b5130ea38
coc.nvim directory: /Users/neerajensritharan/.vim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-08-10T13:15:22.447 INFO (pid:25962) [services] - registered service "languageserver.ccls"
2022-08-10T13:15:22.519 ERROR (pid:25962) [extensions] - Error on active extension coc-prettier: TypeError: import_coc6.window.onDidChangeActiveTextEditor is not a function
    at PrettierEditService.registerDisposables (/Users/neerajensritharan/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:4506:49)
    at Object.activate (/Users/neerajensritharan/.config/coc/extensions/node_modules/coc-prettier/lib/index.js:5044:153)
    at /Users/neerajensritharan/.vim/plugged/coc.nvim/build/index.js:232:1411
    at new Promise (<anonymous>)
```

do you know how to fix? I tried upgrading nvim, but no luck.

**Comment by neery1218** [comment]
Ah, I had to upgrade coc.nvim 😅. Closing, t his is a non-issue
