### ISSUE TITLE
 error: { parser: "postcss" } is deprecated; we now treat it as { parser: "css" }.

### ISSUE THREAD

**Issue by kjf** [neoclide/coc-prettier#26]
I'm seeing this error whenever `stylelintIntegration` is set to true.

In my CocInfo I see this exception a bunch of times

```
SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
[Info  - 09:53:00] Connection to server got closed. Server will restart.
/Users/kevin/.config/coc/extensions/node_modules/coc-stylelint/lib/server.js:6404
		} catch {
```

**Comment by chemzqm** [comment]
We have removed support for legacy linter integration. https://github.com/neoclide/coc-prettier/blob/master/CHANGELOG.md
