### ISSUE TITLE
Unable to install coc-prettier

### ISSUE THREAD

**Issue by numToStr** [neoclide/coc-prettier#57]
When I try to install `coc-prettier` via `let g:coc_global_extensions`, I get this error:

![Screenshot_20200503_184020](https://user-images.githubusercontent.com/24727447/80915136-c8eabc80-8d6d-11ea-8fe6-2a8a332cf1ba.png)

![Screenshot_20200503_184344](https://user-images.githubusercontent.com/24727447/80915165-0d765800-8d6e-11ea-9824-4f1e38a90666.png)

I debug the npm log and I found this
```log
1845 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...2","esprima":"git://g'
1845 verbose stack     at JSON.parse (<anonymous>)
1845 verbose stack     at parseJson (/home/hello/n/lib/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
1845 verbose stack     at /home/hello/n/lib/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
1845 verbose stack     at runMicrotasks (<anonymous>)
1845 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
1846 verbose cwd /tmp/coc-prettier-qKGAyH
1847 verbose Linux 5.6.8-1-MANJARO
1848 verbose argv "/home/hello/n/bin/node" "/home/hello/n/bin/npm" "install" "--ignore-scripts" "--no-lockfile" "--production"
1849 verbose node v12.16.1
1850 verbose npm  v6.13.4
1851 error Unexpected end of JSON input while parsing near '...2","esprima":"git://g'
1852 verbose exit [ 1, true ]
```

**Comment by chemzqm** [comment]
Don't know what's wrong with your npm.

**Comment by Mikhael1729** [comment]
I've had a similar issue. I solved it as follows:

1. Downgrade npm to version 4.6.1: ```npm install -g npm@4.6.1```
2. Open nvim and run: ```:CocInstall coc-prettier```

That's all!

**Comment by numToStr** [comment]
@Mikhael1729 That `npm` is way too old.

**Comment by Mikhael1729** [comment]
> @Mikhael1729 That `npm` is way too old.

Perhaps a newer version works well. I need to try it.

**Comment by numToStr** [comment]
> Perhaps a newer version works well. I need to try it.

IDK but this issue comes with only npm. If you do this it will work.

```vim
Plug "neoclide/coc-prettier", { do: "yarn install --frozen-lockfile" }
```

**Comment by guidiamond** [comment]
> ```viml
> Plug 'neoclide/coc-prettier', { 'do': 'yarn install --frozen-lockfile' }
> ```

use single quotes in everything if you're using vim-plug
