### ISSUE TITLE
Couldn't resolve parser "postcss"

### ISSUE THREAD

**Issue by jose4125** [neoclide/coc-prettier#88]
when I ran `:Prettier` to format my scss file. I got this error, Could you help me fixing it? thanks
```
[coc.nvim]: UnhandledRejection: Couldn't resolve parser "postcss"
Error: Couldn't resolve parser "postcss"
    at resolveParser (/Users/bbb/Sites/rot-project/ui-rot/node_modules/prettier/index.js:11343:15)
    at normalize$1 (/Users/bbb/Sites/rot-project/ui-rot/node_modules/prettier/index.js:11438:18)
    at formatWithCursor (/Users/bbb/Sites/rot-project/ui-rot/node_modules/prettier/index.js:15034:12)
    at /Users/bbb/Sites/rot-project/ui-rot/node_modules/prettier/index.js:51620:12
    at Object.format (/Users/bbb/Sites/rot-project/ui-rot/node_modules/prettier/index.js:51640:12)
    at /Users/bbb/.config/coc/extensions/node_modules/coc-prettier/node_modules/prettier-stylelint/src/index.js:129:30
```

**Comment by nulty** [comment]
I just hit this issue myself.

The issue is that `coc-prettier` is using [`prettier-stylelint`]() to interface with prettier for formatting scss. That project hasn't been updated in 4 years. Recommendation is to switch to [`stylelint-prettier`](https://github.com/prettier/stylelint-prettier) which is under development and maintained by the `prettier` organisation.

[The parser in `prettier-stylelint` is hard coded to use `postcss`](https://github.com/hugomrdias/prettier-stylelint/blob/2e37e73e600a3e01aef9b053c712914f872385d1/src/index.js#L63) but [prettier has changed it's API is require `css` as the parser name.](https://github.com/prettier/prettier/pull/7535/files)

**Comment by nulty** [comment]
I think using the CocConfig flag  `"prettier.onlyUseLocalVersion": true` is a work around but you'll need it installed locally of course.
